spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}
apiDolar:
  baseUrl: https://dolarapi.com/v1
finnHub:
  baseUrl: https://finnhub.io/api/v1
springDoc:
  apiDocs:
    enabled: true
    path: /api/v3/api-docs
  swaggerUi:
    enabled: true
    path: /doc/swagger-ui.html